<?php
$this->headTitle('Regisration');
$this->mainMenu()->setActiveItemId('users');
$this->pageBreadcrumbs()->setItems([
            'Gallery'=>$this->url('gallery'),
            'Registration'=>$this->url('registration'),
            ]);
$form->get('login')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ]);
$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'John Doe'
    ]);
$form->get('password')->setAttributes([
    'class'=>'form-control'
    ]);
$form->get('confirm_password')->setAttributes([
    'class'=>'form-control'
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Registration</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('login')); ?>
            <?= $this->formElement($form->get('login')); ?>
            <?= $this->formElementErrors($form->get('login')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div> 