<?php
$this->headTitle('Manage Alboms');
$this->mainMenu()->setActiveItemId('home');
$this->pageBreadcrumbs()->setItems([
            'Gallery'=>$this->url('gallery'),
            ]);
?>

<h1>Manage Alboms</h1>

<table class="table table-striped">

   <tr>
        <th>Albom Name</th>
        <th>Image</th>
        <th>Authors</th>  
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($alboms as $albom): ?>
    <?php// var_dump($albom);echo "||||||||||||||||||||||||||||"; ?>
    <tr>
        <td>
            <a href="<?//= $this->url('alboms', ['action'=>'view', 'id'=>$alboms->getId()]); ?>">
                <?= $this->escapeHtml($albom->getName()); ?>
            </a> 
        </td>
        <td>
            <div class="img-thumbnail">
                <img src="<?= $this->url('alboms', ['action'=>'file'], 
                    ['query'=>['name'=>$this->escapeHtml($albom->getImage()), 'thumbnail'=>true]]); ?>" >
            </div>
        </td>
        <td><?= $this->escapeHtml($albomManager->convertAuthorsToString($albom)); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('alboms', 
                    ['action'=>'edit', 'id'=>$albom->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-info" href="<?= $this->url('alboms', 
                    ['action'=>'add-author', 'id'=>$albom->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Add Author
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
    
    <?= $this->paginationControl($alboms,
                    'Sliding',
                    'application/partial/paginator', 
                    array('route' => 'application')); ?>
    
</table>
